version: '3.7'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 7777:8080
      - 5005:5005
    volumes:
      - .:/app
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -XX:+UseContainerSupport -XX:MaxRAMFraction=1 -XshowSettings:vm"
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grip
    ports:
      - 54320:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
